import { useMemo, useState } from 'react'
import { profileAvatarShows, searchProfileAvatars, type ProfileAvatarRef } from '../../data/profileAvatars'
import SelectMenu from '../ui/SelectMenu'
import ProfileAvatar from './ProfileAvatar'

export default function AvatarGallery({ selected, onSelect, onClose }: { selected?: ProfileAvatarRef; onSelect: (avatar: ProfileAvatarRef) => void; onClose: () => void }) {
  const [query, setQuery] = useState(''); const [show, setShow] = useState(''); const [limit, setLimit] = useState(120)
  const avatars = useMemo(() => searchProfileAvatars(query, show), [query, show]); const visible = avatars.slice(0, limit)
  return <div role="dialog" aria-modal="true" aria-label="Choose profile avatar" onKeyDown={(event) => event.key === 'Escape' && onClose()} className="fixed inset-0 z-[10070] grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="flex max-h-[90vh] w-full max-w-5xl flex-col rounded-3xl border border-white/15 bg-[#161616] shadow-2xl"><div className="border-b border-white/10 p-5"><div className="flex items-center justify-between gap-4"><div><h3 className="text-xl font-black text-white">Choose an avatar</h3><p className="mt-1 text-sm text-white/55">Retired Netflix profile icons · {avatars.length} matches</p></div><button onClick={onClose} className="rounded-lg px-3 py-2 text-white/65 hover:bg-white/10 hover:text-white">Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_16rem]"><input autoFocus value={query} onChange={(event) => { setQuery(event.target.value); setLimit(120) }} placeholder="Search characters or shows" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-white/40" /><SelectMenu value={show} onChange={(event) => { setShow(event.target.value); setLimit(120) }} aria-label="Filter avatars by show" className="w-full"><option value="">All shows</option>{profileAvatarShows.map((item) => <option key={item} value={item}>{item}</option>)}</SelectMenu></div></div><div className="overflow-y-auto p-5"><div className="grid grid-cols-4 gap-3 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10">{visible.map((avatar) => <button type="button" key={avatar.id} onClick={() => onSelect({ source: 'netflix-retired', avatarId: avatar.id })} aria-label={`${avatar.name} — ${avatar.show}`} className={`rounded-xl p-1.5 text-left transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white ${selected?.source === 'netflix-retired' && selected.avatarId === avatar.id ? 'bg-white/15 ring-2 ring-white' : ''}`}><ProfileAvatar name={avatar.name} avatarRef={{ source: 'netflix-retired', avatarId: avatar.id }} size="md" className="h-full w-full" /><span className="mt-1 block truncate text-[10px] text-white/65">{avatar.name}</span></button>)}</div>{avatars.length === 0 && <p className="py-12 text-center text-sm text-white/50">No matching avatars.</p>}{visible.length < avatars.length && <button onClick={() => setLimit((value) => value + 120)} className="mx-auto mt-6 block rounded-xl border border-white/15 px-4 py-2 text-sm font-semibold text-white hover:bg-white/10">Show more</button>}<p className="mt-7 text-center text-xs leading-5 text-white/35">Icons catalogued from Bring Back Netflix Icons. Artwork belongs to Netflix and its respective rights holders.</p></div></div></div>
}
