use crate::db::Database;
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NormalizeProviderMetadataRequest {
    pub kind: MediaKind,
    pub details: ProviderDetails,
    pub input: AddonMediaInput,
    /// Generated by the compatibility layer so the native and legacy paths
    /// preserve the same timestamp format and cache payload shape.
    pub updated_at: String,
}

#[derive(Clone, Copy, Debug, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MediaKind {
    Movie,
    Show,
    Anime,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderDetails {
    pub id: String,
    pub title: String,
    pub original_title: Option<String>,
    pub year: Option<i64>,
    pub overview: Option<String>,
    #[serde(default)]
    pub genres: Vec<String>,
    pub runtime: Option<i64>,
    pub rating: Option<f64>,
    pub poster: Option<String>,
    pub backdrop: Option<String>,
    pub logo: Option<String>,
    pub certification: Option<String>,
    pub original_language: Option<String>,
    pub imdb_id: Option<String>,
    pub tmdb_id: Option<NumericId>,
    pub tvdb_id: Option<NumericId>,
    pub provider: Option<String>,
    #[serde(default)]
    pub seasons: Vec<ProviderSeason>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum NumericId {
    Number(f64),
    String(String),
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderSeason {
    pub season_number: i64,
    pub name: String,
    #[serde(default)]
    pub episode_count: i64,
    pub poster: Option<String>,
    pub overview: Option<String>,
    pub air_date: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AddonMediaInput {
    pub addon_id: String,
    pub id: Option<String>,
    pub imdb_id: Option<String>,
    pub tmdb_id: Option<NumericId>,
    pub tvdb_id: Option<NumericId>,
    pub trakt_id: Option<i64>,
    pub simkl_id: Option<i64>,
    pub anilist_id: Option<NumericId>,
    pub mal_id: Option<NumericId>,
}

/// Stable lookup order for persisted normalized metadata. This mirrors the
/// existing frontend cache contract and remains deliberately separate from
/// provider ID resolution.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetadataLookup {
    pub id: Option<String>,
    pub imdb_id: Option<String>,
    pub tmdb_id: Option<i64>,
    pub tvdb_id: Option<i64>,
    pub anilist_id: Option<i64>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppMediaItem {
    pub id: String,
    #[serde(rename = "type")]
    pub media_type: &'static str,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub poster: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backdrop: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
    pub genres: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rating: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub age_rating: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tmdb_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tvdb_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imdb_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trakt_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub simkl_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub anilist_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mal_id: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seasons: Option<Vec<AppSeason>>,
    pub source_metadata_provider: &'static str,
    pub source_addon_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_addon_item_id: Option<String>,
    pub updated_at: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppSeason {
    pub id: String,
    pub season_number: i64,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub poster: Option<String>,
    pub episode_count: i64,
    pub episodes: Vec<()>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub air_date: Option<String>,
}

pub fn normalize_provider_metadata(request: NormalizeProviderMetadataRequest) -> AppMediaItem {
    let details = request.details;
    let input = request.input;
    // These source-selection rules deliberately mirror the established
    // JavaScript normalizer: movies use `||`, shows use `??` for TMDB/TVDB.
    // Resolve only after selecting the source, so a malformed but present ID
    // remains malformed rather than unexpectedly falling through to another.
    let detail_id_or_input = |detail: &Option<NumericId>, input: &Option<NumericId>| {
        detail
            .as_ref()
            .filter(|value| id_is_truthy(value))
            .or(input.as_ref())
            .and_then(number_id)
    };
    let detail_id_or_input_nullish = |detail: &Option<NumericId>, input: &Option<NumericId>| {
        detail.as_ref().or(input.as_ref()).and_then(number_id)
    };
    let (tmdb_id, tvdb_id) = match request.kind {
        MediaKind::Movie => (
            detail_id_or_input(&details.tmdb_id, &input.tmdb_id),
            detail_id_or_input(&details.tvdb_id, &input.tvdb_id),
        ),
        MediaKind::Show | MediaKind::Anime => (
            detail_id_or_input_nullish(&details.tmdb_id, &input.tmdb_id),
            detail_id_or_input_nullish(&details.tvdb_id, &input.tvdb_id),
        ),
    };
    let imdb_id = details
        .imdb_id
        .filter(|value| !value.is_empty())
        .or(input.imdb_id);
    let anilist_id = input.anilist_id.as_ref().and_then(number_id);
    let mal_id = input.mal_id.as_ref().and_then(number_id);
    let source_metadata_provider = if details.provider.as_deref() == Some("tvdb") {
        "tvdb"
    } else {
        "tmdb"
    };

    let (id, media_type, seasons) = match request.kind {
        MediaKind::Movie => (
            tmdb_id
                .map(|value| format!("app_tmdb_movie_{value}"))
                .unwrap_or_else(|| {
                    format!(
                        "app_movie_{}",
                        imdb_id.clone().or(input.id.clone()).unwrap_or_default()
                    )
                }),
            "movie",
            None,
        ),
        MediaKind::Show | MediaKind::Anime => {
            let id = tvdb_id
                .map(|value| format!("app_tvdb_{value}"))
                .or_else(|| tmdb_id.map(|value| format!("app_tmdb_tv_{value}")))
                .unwrap_or_else(|| {
                    format!(
                        "app_show_{}",
                        imdb_id.clone().or(input.id.clone()).unwrap_or_default()
                    )
                });
            let prefix = if let Some(value) = tvdb_id {
                format!("tvdb_{value}")
            } else if let Some(value) = tmdb_id {
                format!("tmdb_{value}")
            } else {
                format!("media_{}", details.id)
            };
            let seasons = details
                .seasons
                .into_iter()
                .map(|season| AppSeason {
                    id: format!("{prefix}_s{}", season.season_number),
                    season_number: season.season_number,
                    title: season.name,
                    overview: season.overview,
                    poster: season.poster,
                    episode_count: season.episode_count,
                    episodes: Vec::new(),
                    air_date: season.air_date,
                })
                .collect();
            (
                id,
                if matches!(request.kind, MediaKind::Anime) {
                    "anime"
                } else {
                    "show"
                },
                Some(seasons),
            )
        }
    };

    AppMediaItem {
        id,
        media_type,
        title: details.title,
        original_title: details.original_title,
        year: details.year,
        overview: details.overview,
        poster: details.poster,
        backdrop: details.backdrop,
        logo: details.logo,
        genres: details.genres,
        runtime: if media_type == "movie" {
            details.runtime
        } else {
            None
        },
        rating: details.rating,
        age_rating: details.certification,
        original_language: details.original_language,
        tmdb_id,
        tvdb_id,
        imdb_id,
        trakt_id: input.trakt_id,
        simkl_id: input.simkl_id,
        anilist_id,
        mal_id,
        seasons,
        source_metadata_provider,
        source_addon_id: input.addon_id,
        source_addon_item_id: input.id,
        updated_at: request.updated_at,
    }
}

pub fn get_persisted_by_ids(db: &Database, lookup: &MetadataLookup) -> Option<String> {
    let conn = db.conn.lock().ok()?;
    lookup_raw_metadata(&conn, lookup)
}

pub fn get_persisted_for_addon(
    db: &Database,
    addon_id: String,
    addon_item_id: String,
) -> Option<String> {
    let conn = db.conn.lock().ok()?;
    conn.query_row(
        "SELECT m.raw_json FROM app_media m JOIN addon_media_mappings a ON a.local_media_id=m.id WHERE a.addon_id=?1 AND a.addon_item_id=?2",
        rusqlite::params![addon_id, addon_item_id],
        |row| row.get(0),
    ).ok()
}

pub fn get_persisted_by_ids_batch(
    db: &Database,
    lookups: Vec<MetadataLookup>,
) -> Vec<Option<String>> {
    let conn = match db.conn.lock() {
        Ok(conn) => conn,
        Err(_) => return lookups.into_iter().map(|_| None).collect(),
    };
    lookups
        .iter()
        .map(|lookup| lookup_raw_metadata(&conn, lookup))
        .collect()
}

fn lookup_raw_metadata(conn: &rusqlite::Connection, lookup: &MetadataLookup) -> Option<String> {
    if let Some(id) = lookup.id.as_deref() {
        if let Ok(json) = conn.query_row(
            "SELECT raw_json FROM app_media WHERE id = ?1",
            [id],
            |row| row.get(0),
        ) {
            return Some(json);
        }
    }
    if let Some(imdb_id) = lookup.imdb_id.as_deref().filter(|value| !value.is_empty()) {
        if let Ok(json) = conn.query_row(
            "SELECT raw_json FROM app_media WHERE imdb_id = ?1",
            [imdb_id],
            |row| row.get(0),
        ) {
            return Some(json);
        }
    }
    for (column, value) in [
        ("tmdb_id", lookup.tmdb_id),
        ("tvdb_id", lookup.tvdb_id),
        ("anilist_id", lookup.anilist_id),
    ] {
        if let Some(value) = value.filter(|value| *value > 0) {
            let sql = format!("SELECT raw_json FROM app_media WHERE {column} = ?1");
            if let Ok(json) = conn.query_row(&sql, [value], |row| row.get(0)) {
                return Some(json);
            }
        }
    }
    None
}

pub fn delete_persisted_metadata(
    db: &Database,
    addon_id: String,
    addon_item_id: String,
) -> Result<(), String> {
    let conn = db.conn.lock().map_err(|error| error.to_string())?;
    let transaction = conn
        .unchecked_transaction()
        .map_err(|error| error.to_string())?;
    let local_media_id: Option<String> = transaction.query_row(
        "SELECT local_media_id FROM addon_media_mappings WHERE addon_id = ?1 AND addon_item_id = ?2",
        rusqlite::params![addon_id, addon_item_id],
        |row| row.get(0),
    ).ok();
    if let Some(local_media_id) = local_media_id {
        for table in [
            "app_seasons",
            "app_episodes",
            "anime_season_mappings",
            "anime_episode_mappings",
        ] {
            transaction
                .execute(
                    &format!("DELETE FROM {table} WHERE local_media_id = ?1"),
                    [&local_media_id],
                )
                .map_err(|error| error.to_string())?;
        }
        transaction
            .execute("DELETE FROM app_media WHERE id = ?1", [&local_media_id])
            .map_err(|error| error.to_string())?;
        transaction
            .execute(
                "DELETE FROM addon_media_mappings WHERE local_media_id = ?1",
                [&local_media_id],
            )
            .map_err(|error| error.to_string())?;
    }
    transaction.commit().map_err(|error| error.to_string())
}

pub fn hard_reset_anime_metadata(db: &Database, local_media_id: String) -> Result<(), String> {
    let conn = db.conn.lock().map_err(|error| error.to_string())?;
    let transaction = conn
        .unchecked_transaction()
        .map_err(|error| error.to_string())?;
    for table in [
        "app_seasons",
        "app_episodes",
        "anime_season_mappings",
        "anime_episode_mappings",
        "metadata_resolution_log",
    ] {
        transaction
            .execute(
                &format!("DELETE FROM {table} WHERE local_media_id = ?1"),
                [&local_media_id],
            )
            .map_err(|error| error.to_string())?;
    }
    transaction
        .execute(
            "UPDATE app_media SET raw_json = NULL, updated_at = NULL WHERE id = ?1",
            [&local_media_id],
        )
        .map_err(|error| error.to_string())?;
    transaction.commit().map_err(|error| error.to_string())
}

pub fn clear_persisted_metadata(db: &Database) -> Result<(), String> {
    let conn = db.conn.lock().map_err(|error| error.to_string())?;
    conn.execute_batch("DELETE FROM app_episodes; DELETE FROM app_seasons; DELETE FROM addon_media_mappings; DELETE FROM app_media; DELETE FROM metadata_resolution_log;")
        .map_err(|error| error.to_string())
}

pub fn save_persisted_metadata(
    db: &Database,
    media_json: String,
    addon_id: String,
    addon_item_id: String,
    media_type: String,
) -> Result<(), String> {
    let media: serde_json::Value =
        serde_json::from_str(&media_json).map_err(|error| error.to_string())?;
    let id = media
        .get("id")
        .and_then(|value| value.as_str())
        .ok_or("Missing media id")?;
    let title = media
        .get("title")
        .and_then(|value| value.as_str())
        .ok_or("Missing media title")?;
    let updated_at = media
        .get("updatedAt")
        .and_then(|value| value.as_str())
        .unwrap_or("");
    let text = |key: &str| media.get(key).and_then(|value| value.as_str());
    let integer = |key: &str| media.get(key).and_then(|value| value.as_i64());
    let real = |key: &str| media.get(key).and_then(|value| value.as_f64());
    let genres = media
        .get("genres")
        .map(ToString::to_string)
        .unwrap_or_else(|| "[]".into());
    let provider = text("sourceMetadataProvider").unwrap_or("fallback_addon");
    let conn = db.conn.lock().map_err(|error| error.to_string())?;
    let transaction = conn
        .unchecked_transaction()
        .map_err(|error| error.to_string())?;
    transaction.execute(
        "INSERT OR REPLACE INTO app_media (id, media_type, title, original_title, localized_title, year, overview, poster, backdrop, logo, genres_json, runtime, rating, age_rating, language, country, tmdb_id, tvdb_id, imdb_id, trakt_id, simkl_id, anilist_id, mal_id, source_metadata_provider, source_addon_id, raw_json, updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20,?21,?22,?23,?24,?25,?26,?27)",
        rusqlite::params![id, media_type, title, text("originalTitle"), text("localizedTitle"), integer("year"), text("overview"), text("poster"), text("backdrop"), text("logo"), genres, integer("runtime"), real("rating"), text("ageRating"), text("language"), text("country"), integer("tmdbId"), integer("tvdbId"), text("imdbId"), integer("traktId"), integer("simklId"), integer("anilistId"), integer("malId"), provider, addon_id, media_json, updated_at],
    ).map_err(|error| error.to_string())?;
    transaction
        .execute("DELETE FROM app_seasons WHERE local_media_id = ?1", [id])
        .map_err(|error| error.to_string())?;
    transaction
        .execute("DELETE FROM app_episodes WHERE local_media_id = ?1", [id])
        .map_err(|error| error.to_string())?;
    if let Some(seasons) = media.get("seasons").and_then(|value| value.as_array()) {
        for season in seasons {
            let season_id = season
                .get("id")
                .and_then(|value| value.as_str())
                .unwrap_or("");
            transaction.execute(
                "INSERT OR REPLACE INTO app_seasons (id, local_media_id, season_number, title, overview, poster, episode_count, raw_json, updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9)",
                rusqlite::params![season_id, id, season.get("seasonNumber").and_then(|value| value.as_i64()), season.get("title").and_then(|value| value.as_str()), season.get("overview").and_then(|value| value.as_str()), season.get("poster").and_then(|value| value.as_str()), season.get("episodeCount").and_then(|value| value.as_i64()), season.to_string(), updated_at],
            ).map_err(|error| error.to_string())?;
            if let Some(episodes) = season.get("episodes").and_then(|value| value.as_array()) {
                for episode in episodes {
                    transaction.execute(
                        "INSERT OR REPLACE INTO app_episodes (id, local_media_id, season_id, season_number, episode_number, absolute_episode_number, title, overview, still, air_date, runtime, tmdb_id, tvdb_id, anilist_id, raw_json, updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16)",
                        rusqlite::params![episode.get("id").and_then(|value| value.as_str()), id, season_id, episode.get("seasonNumber").and_then(|value| value.as_i64()), episode.get("episodeNumber").and_then(|value| value.as_i64()), episode.get("absoluteEpisodeNumber").and_then(|value| value.as_i64()), episode.get("title").and_then(|value| value.as_str()), episode.get("overview").and_then(|value| value.as_str()), episode.get("still").and_then(|value| value.as_str()), episode.get("airDate").and_then(|value| value.as_str()), episode.get("runtime").and_then(|value| value.as_i64()), episode.get("tmdbId").and_then(|value| value.as_i64()), episode.get("tvdbId").and_then(|value| value.as_i64()), episode.get("anilistId").and_then(|value| value.as_i64()), episode.to_string(), updated_at],
                    ).map_err(|error| error.to_string())?;
                }
            }
        }
    }
    let mapping_id = format!("{addon_id}:{addon_item_id}");
    transaction.execute(
        "INSERT OR REPLACE INTO addon_media_mappings (id, addon_id, addon_item_id, local_media_id, media_type, created_at, updated_at) VALUES (?1,?2,?3,?4,?5,COALESCE((SELECT created_at FROM addon_media_mappings WHERE id=?1),datetime('now')),datetime('now'))",
        rusqlite::params![mapping_id, addon_id, addon_item_id, id, media_type],
    ).map_err(|error| error.to_string())?;
    let log_id = format!(
        "{addon_id}:{addon_item_id}:{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis()
    );
    transaction.execute(
        "INSERT INTO metadata_resolution_log (id, addon_id, addon_item_id, local_media_id, status, reason, created_at) VALUES (?1,?2,?3,?4,?5,?6,datetime('now'))",
        rusqlite::params![log_id, addon_id, addon_item_id, id, if provider == "fallback_addon" { "fallback" } else { "resolved" }, provider],
    ).map_err(|error| error.to_string())?;
    transaction.commit().map_err(|error| error.to_string())
}

fn number_id(value: &NumericId) -> Option<i64> {
    let raw = match value {
        NumericId::Number(value) => {
            return (*value)
                .is_finite()
                .then_some(*value as i64)
                .filter(|value| *value > 0)
        }
        NumericId::String(value) => value.trim(),
    };
    let prefix_length = raw.bytes().take_while(u8::is_ascii_alphabetic).count();
    let without_prefix = if prefix_length > 0 {
        raw[prefix_length..].strip_prefix('-').unwrap_or(raw)
    } else {
        raw
    };
    without_prefix
        .parse::<f64>()
        .ok()
        .filter(|value| value.is_finite() && *value > 0.0)
        .map(|value| value as i64)
}

fn id_is_truthy(value: &NumericId) -> bool {
    match value {
        NumericId::Number(value) => *value != 0.0,
        NumericId::String(value) => !value.is_empty(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temporary_database() -> (Database, std::path::PathBuf) {
        let directory = std::env::temp_dir().join(format!(
            "aurales-metadata-core-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos(),
        ));
        let database = Database::new(directory.clone()).unwrap();
        (database, directory)
    }

    #[test]
    fn accepts_provider_prefixed_ids_and_uses_tvdb_show_identity() {
        let request: NormalizeProviderMetadataRequest = serde_json::from_value(serde_json::json!({
            "kind": "show", "updatedAt": "2026-09-09T00:00:00.000Z",
            "details": { "id": "12", "title": "Example", "genres": [], "tvdbId": "tvdb-42", "tmdbId": "tmdb-7", "seasons": [] },
            "input": { "addonId": "addon", "id": "source" }
        })).unwrap();
        let item = normalize_provider_metadata(request);
        assert_eq!(item.id, "app_tvdb_42");
        assert_eq!(item.source_metadata_provider, "tmdb");
    }

    #[test]
    fn rejects_non_positive_and_malformed_ids() {
        for value in ["0", "-1", "undefined", "foo:12"] {
            assert_eq!(number_id(&NumericId::String(value.into())), None);
        }
    }

    #[test]
    fn persists_and_removes_metadata_without_changing_lookup_order() {
        let (database, directory) = temporary_database();
        let media = serde_json::json!({
            "id": "app_tmdb_tv_7", "title": "Example", "type": "show", "genres": ["Drama"],
            "tmdbId": 7, "imdbId": "tt007", "sourceMetadataProvider": "tmdb",
            "updatedAt": "2026-09-09T00:00:00.000Z",
            "seasons": [{ "id": "tmdb_7_s1", "seasonNumber": 1, "title": "Season 1", "episodeCount": 1,
                "episodes": [{ "id": "tv_7_s1e1", "seasonNumber": 1, "episodeNumber": 1, "title": "Pilot" }] }]
        }).to_string();
        save_persisted_metadata(
            &database,
            media.clone(),
            "addon".into(),
            "item".into(),
            "show".into(),
        )
        .unwrap();
        assert_eq!(
            get_persisted_for_addon(&database, "addon".into(), "item".into()),
            Some(media.clone())
        );
        assert_eq!(
            get_persisted_by_ids(
                &database,
                &MetadataLookup {
                    id: None,
                    imdb_id: None,
                    tmdb_id: Some(7),
                    tvdb_id: None,
                    anilist_id: None
                }
            ),
            Some(media)
        );
        delete_persisted_metadata(&database, "addon".into(), "item".into()).unwrap();
        assert_eq!(
            get_persisted_by_ids(
                &database,
                &MetadataLookup {
                    id: Some("app_tmdb_tv_7".into()),
                    imdb_id: None,
                    tmdb_id: None,
                    tvdb_id: None,
                    anilist_id: None
                }
            ),
            None
        );
        drop(database);
        std::fs::remove_dir_all(directory).unwrap();
    }
}
