import { useState } from 'react'
import { getSyncConfig, getSyncOutbox, setSyncConfig, syncNow } from '../../services/sync/auralesSync'
import EncryptedVaultSettings from './EncryptedVaultSettings'

export default function AuralesSyncSettings() {
  const [config, setConfig] = useState(() => getSyncConfig()); const [message, setMessage] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('')
  const save = () => { setSyncConfig(config); setMessage('Saved on this device') }
  const authenticate = async (action: 'register' | 'login') => { try { if (!config.endpoint) throw new Error('Enter the Sync service URL first'); const response = await fetch(`${config.endpoint.replace(/\/$/, '')}/v1/auth/${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); const result = await response.json() as { accessToken?: string; error?: string }; if (!response.ok || !result.accessToken) throw new Error(result.error || 'Authentication failed'); const next = { ...config, accessToken: result.accessToken }; setConfig(next); setSyncConfig(next); setPassword(''); setMessage(action === 'register' ? 'Account created and connected' : 'Connected') } catch (error) { setMessage(error instanceof Error ? error.message : 'Authentication failed') } }
  const sync = () => {
    if (!config.accessToken) { setMessage('Create an account, sign in, or paste an access token first.'); return }
    setSyncConfig(config)
    void syncNow().then((result) => setMessage(`Synced ${result.uploaded} pending changes`)).catch((error) => setMessage(error.message))
  }
  return <section className="overflow-hidden rounded-2xl border border-white/[0.07] bg-white/[0.025]"><div className="border-b border-white/[0.06] px-6 py-5"><h2 className="font-semibold text-white">Aurales Sync</h2><p className="mt-1 text-sm text-white/60">Syncs durable Aurales profile state. Provider credentials, cache data, and temporary stream URLs are never included.</p></div><div className="space-y-4 px-6 py-5"><label className="block text-sm text-white/65">Sync service URL<input value={config.endpoint || ''} onChange={(event) => setConfig({ ...config, endpoint: event.target.value })} placeholder="https://sync.example.com" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-white outline-none placeholder:text-white/30" /></label>{!config.accessToken && <div className="grid gap-3 rounded-2xl border border-white/[.08] bg-black/[.12] p-4 sm:grid-cols-2"><label className="text-sm text-white/65">Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-white outline-none" /></label><label className="text-sm text-white/65">Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" minLength={12} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-white outline-none" /></label><div className="sm:col-span-2 flex gap-2"><button onClick={() => authenticate('register')} className="rounded-xl border border-white/15 px-3 py-2 text-sm text-white/75">Create account</button><button onClick={() => authenticate('login')} className="rounded-xl border border-white/15 px-3 py-2 text-sm text-white/75">Sign in</button></div></div>}<label className="block text-sm text-white/65">Access token<input value={config.accessToken || ''} onChange={(event) => setConfig({ ...config, accessToken: event.target.value })} type="password" placeholder="Created automatically or paste an existing token" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-white outline-none placeholder:text-white/30" /></label><div className="flex flex-wrap items-center gap-3"><button onClick={save} className="rounded-xl border border-white/15 px-4 py-2 text-sm font-semibold text-white">Save</button><button onClick={sync} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-black">Sync Now</button><span className="text-xs text-white/45">{message || `${getSyncOutbox().length} pending changes`}</span></div><EncryptedVaultSettings connected={Boolean(config.accessToken)} onMessage={setMessage} /></div></section>
}
