import { useEffect, useState } from 'react'
import { createProfile, deleteProfile, getActiveProfile, getProfiles, PROFILE_CHANGED_EVENT, setActiveProfile, updateProfile, type AuralesProfile } from '../../services/profiles'
import type { ProfileAvatarRef } from '../../data/profileAvatars'
import AvatarGallery from '../profiles/AvatarGallery'
import ProfileAvatar from '../profiles/ProfileAvatar'

const FALLBACKS = ['✦', '◉', '◆', '●', '▲', '☾', '✺', '♢']; const ACCENTS = ['#8b5cf6', '#0ea5e9', '#14b8a6', '#f59e0b', '#ef4444', '#ec4899']
export default function ProfilesSettings() {
  const [profiles, setProfiles] = useState(getProfiles), [selectedId, setSelectedId] = useState<string | null>(null), [creating, setCreating] = useState(false)
  const refresh = () => setProfiles(getProfiles()); useEffect(() => { window.addEventListener(PROFILE_CHANGED_EVENT, refresh); return () => window.removeEventListener(PROFILE_CHANGED_EVENT, refresh) }, [])
  const selected = profiles.find((profile) => profile.id === selectedId)
  if (selected) return <Editor profile={selected} onBack={() => { refresh(); setSelectedId(null) }} />
  return <><section className="mx-auto w-full max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-white/40">Personalization</p><h2 className="mt-2 text-3xl font-black text-white">Who’s watching?</h2><p className="mt-2 text-sm text-white/60">Every profile is a separate Aurales user space: its provider logins, add-ons, API keys, settings, progress, watchlist, Discover taste, and playback preferences stay private.</p><div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{profiles.map((profile) => <button key={profile.id} onClick={() => setSelectedId(profile.id)} className={`min-h-52 rounded-3xl border p-6 text-left transition hover:-translate-y-0.5 hover:bg-white/[.07] ${profile.id === getActiveProfile().id ? 'border-white/35 bg-white/[.09]' : 'border-white/[.09] bg-white/[.025]'}`}><ProfileAvatar {...profile} /><p className="mt-8 text-lg font-bold text-white">{profile.name}</p><p className="mt-1 text-xs text-white/45">{profile.id === getActiveProfile().id ? 'Active profile' : 'Profile'}</p></button>)}<button onClick={() => setCreating(true)} className="min-h-52 rounded-3xl border border-dashed border-white/15 bg-white/[.018] p-6 text-left hover:bg-white/[.05]"><span className="grid h-14 w-14 place-items-center rounded-[28%] bg-white/[.08] text-3xl text-white/70">+</span><p className="mt-8 text-lg font-bold text-white">Add Profile</p><p className="mt-1 text-sm text-white/45">Starts with no connected accounts</p></button></div></section>{creating && <ProfileForm onClose={() => setCreating(false)} onSave={(profile) => { const created = createProfile(profile.name, profile.avatar, profile.accent, profile.avatarRef); refresh(); setCreating(false); setSelectedId(created.id) }} />}</>
}
function ProfileForm({ initial, onClose, onSave }: { initial?: AuralesProfile; onClose: () => void; onSave: (profile: { name: string; avatar: string; accent: string; avatarRef?: ProfileAvatarRef }) => void }) {
  const [name, setName] = useState(initial?.name || ''), [avatar, setAvatar] = useState(initial?.avatar || FALLBACKS[0]), [accent, setAccent] = useState(initial?.accent || ACCENTS[0]), [avatarRef, setAvatarRef] = useState<ProfileAvatarRef | undefined>(initial?.avatarRef), [gallery, setGallery] = useState(false)
  return <><div role="dialog" aria-modal="true" aria-label={initial ? 'Edit profile' : 'Create profile'} className="fixed inset-0 z-[10050] grid place-items-center bg-black/70 p-5 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); if (name.trim()) onSave({ name: name.trim(), avatar, accent, avatarRef }) }} className="w-full max-w-md rounded-3xl border border-white/15 bg-[#161616] p-6 shadow-2xl"><h3 className="text-xl font-black text-white">{initial ? 'Edit Profile' : 'Create Profile'}</h3><label className="mt-6 block text-xs font-bold uppercase tracking-wider text-white/45">Profile name<input autoFocus value={name} maxLength={40} onChange={(e) => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-white outline-none" /></label><div className="mt-5 flex items-center gap-3"><ProfileAvatar name={name || 'Profile'} avatar={avatar} avatarRef={avatarRef} accent={accent} /><button type="button" onClick={() => setGallery(true)} className="rounded-xl border border-white/15 px-3 py-2 text-sm text-white hover:bg-white/10">Choose gallery avatar</button></div><Choices label="Avatar fallback" values={FALLBACKS} selected={avatar} onSelect={setAvatar} /><Choices label="Accent" values={ACCENTS} selected={accent} onSelect={setAccent} color /><div className="mt-7 flex justify-end gap-2"><button type="button" onClick={onClose} className="px-4 py-2 text-sm text-white/65">Cancel</button><button disabled={!name.trim()} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-black disabled:opacity-40">{initial ? 'Save Profile' : 'Create Profile'}</button></div></form></div>{gallery && <AvatarGallery selected={avatarRef} onSelect={(ref) => { setAvatarRef(ref); setGallery(false) }} onClose={() => setGallery(false)} />}</>
}
function Editor({ profile, onBack }: { profile: AuralesProfile; onBack: () => void }) { const [editing, setEditing] = useState(false); const switchProfile = async (event: React.MouseEvent<HTMLButtonElement>) => { event.preventDefault(); event.stopPropagation(); await setActiveProfile(profile.id) }; return <><section className="mx-auto w-full max-w-5xl"><button type="button" onClick={onBack} className="mb-7 text-sm font-semibold text-white/55 hover:text-white">← Profiles</button><div className="flex flex-wrap items-center gap-5 rounded-3xl border border-white/[.1] bg-white/[.03] p-6"><ProfileAvatar {...profile} size="lg" /><div><h2 className="text-3xl font-black text-white">{profile.name}</h2><p className="mt-1 text-sm text-white/55">{profile.id === getActiveProfile().id ? 'Active Profile · Personalized' : 'Profile'}</p></div><button type="button" onClick={switchProfile} className="ml-auto rounded-xl border border-white/15 px-4 py-2 text-sm font-bold text-white">{profile.id === getActiveProfile().id ? 'Active' : 'Switch to Profile'}</button></div><section className="mt-5 rounded-3xl border border-white/[.08] bg-white/[.025] p-6"><h3 className="text-lg font-bold text-white">Profile</h3><p className="mt-1 text-sm text-white/55">Choose a Netflix avatar, a name, and a profile accent.</p><button type="button" onClick={() => setEditing(true)} className="mt-5 rounded-xl bg-white px-4 py-2 text-sm font-bold text-black">Edit Profile</button></section><section className="mt-5 rounded-3xl border border-red-400/20 bg-red-400/[.03] p-6"><h3 className="font-bold text-white">Danger Zone</h3><button type="button" disabled={getProfiles().length <= 1} onClick={() => { if (confirm(`Delete “${profile.name}”?`) && deleteProfile(profile.id)) onBack() }} className="mt-4 rounded-xl border border-red-400/35 px-4 py-2 text-sm text-red-200 disabled:opacity-35">Delete Profile</button></section></section>{editing && <ProfileForm initial={profile} onClose={() => setEditing(false)} onSave={(draft) => { updateProfile(profile.id, draft); setEditing(false); onBack() }} />}</> }
function Choices({ label, values, selected, onSelect, color }: { label: string; values: string[]; selected: string; onSelect: (value: string) => void; color?: boolean }) { return <div className="mt-5"><p className="text-xs font-bold uppercase tracking-wider text-white/45">{label}</p><div className="mt-2 flex flex-wrap gap-2">{values.map((value) => <button type="button" key={value} aria-label={`${label} ${value}`} onClick={() => onSelect(value)} className={`grid h-9 w-9 place-items-center rounded-xl border ${selected === value ? 'border-white bg-white/15' : 'border-transparent bg-white/[.06]'}`} style={color ? { backgroundColor: value } : undefined}>{color ? null : value}</button>)}</div></div> }
